Traceback (most recent call last):
  File "ExploitMyUnion.pyw", line 479, in <module>
  File "ExploitMyUnion.pyw", line 470, in localize
WindowsError: [Error 3] Le chemin d'accès spécifié est introuvable: 'ui/*.*'
